#!/bin/sh
set -e

if [ "$1" = configure ]; then
	systemctl daemon-reload >/dev/null 2>&1 || true
	systemctl enable --now cheburprobe-update.timer cheburprobe-update.path >/dev/null 2>&1 || true
	if [ -n "${2:-}" ]; then
		systemctl try-restart cheburprobe.service >/dev/null 2>&1 || true
	fi
fi

exit 0
