[log]
to = "console"
level = "info"
dir = "/var/log/rmqtt"
file = "rmqtt.log"

[plugins]
dir = "rmqtt-plugins/"
default_startups = [
    "rmqtt-auth-http",
    "rmqtt-http-api",
    "rmqtt-retainer",
]

[listener.tcp.external]
addr = "0.0.0.0:1883"
allow_anonymous = false
max_packet_size = "1MB"

[listener.ws.external]
addr = "0.0.0.0:8080"
allow_anonymous = false
max_packet_size = "1MB"

[listener.tcp.internal]
enable = true
addr = "0.0.0.0:11883"
allow_anonymous = false
max_packet_size = "1MB"
